### ISSUE TITLE
インターフェイスの定義について

### ISSUE THREAD

**Issue by adrenaline0206** [adrenaline0206/smart-lending#1]
[goToLink](https://github.com/adrenaline0206/smart-lending/blob/9251e2ad6d2c635a16b360e63aca55fb6bf05276/src/app/pages/home/home.component.ts#L109)を[ここ](https://github.com/adrenaline0206/smart-lending/blob/9251e2ad6d2c635a16b360e63aca55fb6bf05276/src/app/views/view-home/view-home.component.html#L7)と[ここ](https://github.com/adrenaline0206/smart-lending/blob/9251e2ad6d2c635a16b360e63aca55fb6bf05276/src/app/views/view-home/view-home.component.html#L10)で共通利用したっかたが、[emit](https://github.com/adrenaline0206/smart-lending/blob/9251e2ad6d2c635a16b360e63aca55fb6bf05276/src/app/views/view-home/view-home.component.ts#L30
)に渡せる引数は１つなので、goToLinkに引数を２つ指定する方法でなく[urlConfig](https://github.com/adrenaline0206/smart-lending/blob/9251e2ad6d2c635a16b360e63aca55fb6bf05276/src/common/constants/types.ts#L1)と言うインターフェイスを定義する方法を採用した。もっと良い方法があると思うのでコメントプリーズ。

**Comment by hageee** [comment]
URL に　'address' をつけるとか、'tx' をつけるとかは、呼び出し元で判断できることなんで、そこで決定すれば良く無いかな？

```
goToLink(url: string): void {
    window.open(`${ETHER_SCAN_BASE_URL + url}`, '_blank');
  }
```

```
<a (click)="onGoToLink('address/' + contract!.address)">{{ contract?.address }}</a>
```

```
<a (click)="onGoToLink('tx/' + deployTransaction!.hash)">{{ deployTransaction?.hash }}</a>
```

**Comment by adrenaline0206** [comment]
コメントありがとう！確かに呼び出し元で判断できるので、引数からわざわざ分岐処理する必要はないね。
下記のコミットで修正しました。
a8795df231c227907b6d761983a65130d7f89582
